gps: Remove usage of std::shared_ptr<T>::unique()
It has been deprecated in c++17 and removed in c++20.
Fixes:
gps/utils/LocIpc.h:119:43: error: no member named 'unique' in
    'std::shared_ptr<int>'
  119 |         if (nullptr != mSocket && mSocket.unique()) {
      |                                   ~~~~~~~ ^
1 error generated.

Change-Id: I10b2be9d07ede68c4083e6a12f2bd5679f603402